#Fayte Interface layout profile: Default
#Fri Oct 02 19:01:11 PDT 2026
win.Brick\ Townhouse_pos=(433, 339)
win.Stack\ of\ Brains_pos=(790, 780)
win.\ The\ Sow_pos=(423, 301)
win.Timber\ Pile_pos=(566, 435)
win.Wiki_sz=(484, 363)
win.Stockbin_pos=(1530, 630)
win.Cellar\ Entrance_pos=(540, 183)
win.Backpack_pos=(170, 450)
win.Do\ You\ happen\ to\ be..._pos=(1150, 194)
win.Stack\ of\ Crackedbone_pos=(150, 50)
pref.fayte_hud_timer_13_sz=200 24
win.Stack\ of\ Autumngrass_pos=(550, 486)
win.Stack\ of\ Gelatinouslard_pos=(580, 89)
win.Veggiesack_pos=(1729, 20)
win.Barrel_pos=(750, 510)
pref.fayte_hud_timer_5_sz=200 24
win.Name\ container_pos=(920, 509)
pref.fayte_hud_timer_12=R R 20 117
pref.fayte_hud_timer_11=R C 0 137
win.Compost_pos=(481, 507)
win.Stampmill_pos=(1420, 207)
win.Old\ Log_pos=(710, 370)
win.Dinner_pos=(445, 254)
win.Stump_pos=(601, 482)
pref.fayte_hud_store_sz=90 90
pref.fayte_hud_wiki_sz=90 90
win.Trade\ Order_pos=(280, 0)
win.Stake_pos=(460, 153)
win.Craftingclassic__pos=(1640, 660)
pref.fayte_hud_tempers=L R 540 0
win.Trip\ Hammer_pos=(424, 149)
win.Equipment_pos=(1182, 650)
win.Inventoryclassic__pos=(1286, 650)
win.Craft\ window_pos=(839, 529)
win.\ The\ Piglet_pos=(531, 197)
win.F-Belt_locked=false
win.World\ Map_pos=(510, 280)
win.Old-style\ Table_pos=(521, 116)
pref.fayte_hud_misc_ui_gamehint_27_sz=252 36
win.Buy_pos=(1562, 299)
win.Bellpeppersack_pos=(652, 64)
win.Pilgrim's\ Hovel_pos=(388, 148)
win.List\ of\ Hotkeys_pos=(472, 627)
pref.fayte_hud_party_sz=84 140
pref.fayte_hud_buffs=C R -172 82
win.Nailbox_pos=(498, 106)
win.Markers\ &\ alerts_pos=(320, 340)
pref.fayte_hud_timerstart=R C 0 -112
win.Feast_pos=(1100, 670)
win.Cartograph_pos=(816, 382)
win.Wooden\ Box_pos=(1669, 579)
win.Stack\ of\ Branch_pos=(457, 548)
win.Selections_pos=(-130, 230)
win.Mushisack_pos=(1300, 450)
pref.fayte_hud_season=R L 323 0
win.Questionably\ Effective\ Scarecrow_pos=(438, 141)
cfg.action_grid_pos=1875,941
pref.fayte_hud_timer_1_sz=200 24
win.Options_pos=(1300, 193)
win.Hay\ Stack_pos=(444, 94)
win.Stone\ Tower_pos=(1394, 71)
win.02.04\ The\ Sow_pos=(465, 242)
win.Almanac_pos=(980, 40)
win.Timers_sounded=true
pref.fayte_hud_gains=R R 371 396
win.Wooden\ Chest_pos=(538, 367)
win.Baking\ Table_pos=(454, 310)
win.Stack\ of\ Coal_pos=(1070, 610)
win.Brickstove_pos=(600, 430)
cfg.button_panel_pos=0,1085
pref.fayte_hud_skillgoal_sz=304 136
win.Bugsack_pos=(207, 141)
win.Brick\ Stove_pos=(318, 413)
win.NumericBelt_flipped=true
pref.fayte_hud_timer_14_sz=200 24
win.Town\ Bell_pos=(470, 136)
win.mmap_pos=(1603, 110)
win.Brick\ Wall_pos=(494, 195)
cfg.minimap_pos=2004,0
win.Area\ selection_pos=(1647, 1008)
pref.fayte_hud_bar3=L R 380 226
pref.fayte_hud_bar2=C R 156 62
win.Bee\ Skep_pos=(1268, 184)
win.Stack\ of\ Blacksand_pos=(417, 203)
win.Stack\ of\ Dross_pos=(470, 270)
win.Time\ Records_pos=(659, 545)
pref.fayte_hud_bar1=C R 155 0
win.Stack\ of\ Bone_pos=(135, 434)
win.Changelog_pos=(122, 73)
win.Character_pos=(979, 281)
pref.fayte_hud_profpins=R R 384 0
pref.fayte_hud_tempers_sz=304 240
win.Basket\ Press_pos=(1430, 219)
win.Mine\ Support_pos=(483, 154)
win.Key\ name_pos=(338, 204)
pref.fayte_hud_bar1_sz=698 60
win.Stack\ of\ Hay_pos=(330, 340)
win.Dist._pos=(1160, 717)
win.Royal\ Ledger_pos=(660, 437)
win.View\ &\ Performance_pos=(840, 330)
win.Tools\ &\ Automation_pos=(1020, 440)
win.Add\ timer_pos=(1468, 377)
win.Render\ Distance\ Configuration_pos=(433, 187)
win.Declaim_pos=(300, 100)
pref.fayte_hud_equip_sz=281 41
win.Send\ feedback_pos=(360, 420)
win.Ghost\ Rider\ Pack_pos=(160, 450)
pref.fayte_hud_achpins_sz=281 34
pref.fayte_hud_sellist=C R 193 0
win.mmap_locked=false
pref.fayte_hud_timer_10_sz=200 24
pref.fayte_hud_timer_2_sz=200 24
pref.fayte_hud_fight_sz=40 38
win.Nutsack_pos=(1788, 52)
pref.fayte_hud_buttons_sz=384 90
win.Drying\ Rack\ guide_pos=(1004, 520)
win.Stack\ of\ Stone_pos=(684, 107)
win.Anvil_pos=(550, 790)
win.Big\ Autumn\ Pack_pos=(162, 186)
pref.fayte_hud_misc_ui_land_9_sz=293 379
pref.fayte_hud_skillgoal=R L 0 346
pref.fayte_hud_gains_sz=279 425
win.Inspect_pos=(1258, 461)
win.Stack\ of\ Rubble_pos=(549, 166)
win.Salem\ Store_pos=(568, 245)
win.Oiling\ Trough_pos=(300, 100)
win.BEAR_pos=(250, 100)
win.Countryside\ Cupboard_pos=(485, 64)
pref.fayte_hud_timer_7_sz=200 24
win.Barkbinder_pos=(1439, 440)
pref.fayte_hud_stance=C R -50 118
win.Farmer's\ House_pos=(367, 128)
win.Stack\ of\ Limestone_pos=(986, 67)
win.Press_pos=(485, 117)
win.Grindstone_pos=(374, 100)
win.Garlicsack_pos=(154, 159)
pref.fayte_hud_cravings_sz=129 63
win.Invitation_pos=(300, 100)
win.\ The\ Sheep_pos=(980, 460)
win.Bread\ Oven_pos=(296, 101)
win.Kiln_pos=(1060, 600)
win.Meatsmoker_pos=(419, 101)
pref.fayte_hud_bar2_sz=698 60
win.Pile\ of\ Wood_pos=(774, 216)
pref.fayte_hud_equip=L R 540 240
win.weightwdg_pos=(666, 772)
win.Stack\ of\ Granite_pos=(133, 486)
win.Tacklebox_pos=(1178, 240)
win.Shellfish-trap_pos=(474, 274)
win.Rename\ bar_pos=(920, 720)
kind=ui
pref.fayte_hud_misc_ui_gamehint_27=L R 0 302
win.Sell_pos=(578, 299)
win.Flowersack_pos=(230, 360)
win.Barn_pos=(657, 443)
win.Claim\ Stake_pos=(446, 138)
pref.fayte_hud_party=L L 0 220
win.Filter_pos=(99, 179)
win.Inventory_pos=(410, 570)
win.Berrysack_pos=(507, 51)
win.A\ Sign_pos=(396, 288)
pref.fayte_hud_timer_11_sz=200 24
win.Alchemy\ Table_pos=(1160, 830)
win.Oil\ Press_pos=(629, 305)
win.Master\ Toolbelt_pos=(110, 810)
win.Big\ Barrel_pos=(590, 400)
pref.fayte_hud_stance_sz=50 50
win.Escape\ Menu_pos=(860, 404)
pref.fayte_hud_timer_3_sz=200 24
win.Turkey\ Coop_pos=(309, 439)
win.Animal_pos=(666, 50)
win.Food\ Trough_pos=(294, 648)
win.Makeshift\ Fence_pos=(598, 388)
win.Season\ changed\!_pos=(276, 337)
pref.fayte_alm_size2=1286,727
win.Timers_pos=(870, 240)
win.Pot_pos=(699, 494)
win.Arrange\ right-click\ options_pos=(1500, 430)
win.Fibresack_pos=(0, 720)
win.Keyring_pos=(529, 322)
win.Cementation\ Furnace_pos=(498, 183)
win.Mine\ Entrance_pos=(295, 101)
pref.fayte_hud_actions_sz=258 184
win.Oven_pos=(509, 224)
win.Abacus_pos=(689, 142)
win.Stack\ of\ Flint_pos=(530, 223)
pref.fayte_hud_misc_wnd=C C -384 61
pref.fayte_hud_misc_invwnd_sz=684 432
win.Drying\ Frame_pos=(820, 670)
win.Journeyman\ Toolbelt_pos=(502, 48)
win.Plank\ Fence_pos=(289, 109)
win.Movable\ while\ locked_pos=(410, 350)
pref.fayte_hud_timer_8_sz=200 24
win.Change\ Name_pos=(869, 655)
pref.fayte_hud_achpins=R C 0 -188
win.Wooden\ Sign_pos=(398, 180)
win.Finery\ Forge_pos=(466, 368)
pref.fayte_hud_fight=L L 0 50
win.Fireplace_pos=(710, 360)
win.Winerack_pos=(1110, 440)
pref.fayte_hud_bar3_sz=140 186
win.Proxy\ CFG_pos=(175, 80)
win.F-Belt_flipped=true
win.Loom_pos=(468, 157)
win.Key\ Bindings_pos=(830, 229)
win.Woven\ Basket_pos=(468, 125)
win.Eggbasket_pos=(1631, 346)
file.chat=\#Fayte Salem chat windows\r\n\#Fri Oct 02 19\:01\:11 PDT 2026\r\n1.size\=540,302\r\n1.pos\=0,926\r\nframeless\=1\r\n1.send\=Area Chat\r\nids\=1\r\n1.channels\=System\\tFayte\\\: Alerts\\tArea Chat\\tParty\\tPrivate chats (any)\r\n
pref.fayte_hud_timers=R C 0 -5
pref.fayte_hud_achtoast=C L -72 120
win.Windmill_pos=(1464, 369)
win.Cauldron_pos=(299, 100)
win.Well_pos=(402, 204)
pref.fayte_hud_cravings=C R -135 118
win.dehydrate_pos=(249, 100)
win.Actions_pos=(0, 220)
win.mmap_sz=(323, 346)
win.Loyal\ Subjects_pos=(1440, 388)
pref.fayte_hud_timer_12_sz=200 24
pref.fayte_hud_timer_4=R C 203 -40
pref.fayte_hud_mainbar=R R 0 0
pref.fayte_hud_timer_3=C R -100 41
win.Compost\ Bin_pos=(884, 260)
pref.fayte_hud_timer_2=C R 34 181
win.Achievements_pos=(164, 105)
pref.fayte_hud_timer_1=C R -100 121
win.Fayte\ Modules_pos=(930, 550)
win.Optionsclassic__pos=(540, 170)
win.Cam\ Control\ Options_pos=(623, 635)
win.Native\ Guide_pos=(231, 411)
win.NumericBelt_locked=false
pref.fayte_hud_timer_4_sz=200 24
pref.fayte_hud_misc_wnd_sz=404 432
win.Canoe_pos=(447, 125)
pref.fayte_hud_timers_sz=290 38
pref.fayte_hud_profpins_sz=269 35
win.Myrtle\ Oak_pos=(635, 311)
win.Coalclamp_pos=(503, 128)
win.Piggy\ Bank_pos=(493, 171)
win.New\ macro_pos=(874, 522)
win.Note\ for\ this\ entry_pos=(1057, 638)
win.Cupboard_pos=(440, 390)
win.Butterfly\ Cage_pos=(548, 322)
win.Kin_pos=(1480, 322)
win.Ore\ Smelter_pos=(1260, 400)
win.Crafting_pos=(490, 680)
win.Tanning\ Tub_pos=(710, 500)
win.Split_pos=(300, 100)
win.\ The\ Boar_pos=(442, 137)
pref.fayte_hud_timer_9_sz=200 24
win.Town_pos=(500, 50)
win.F-Belt_pos=(3, 152)
pref.fayte_hud_sellist_sz=318 172
win.Carpenter's\ Bench_pos=(1090, 340)
pref.fayte_hud_mainbar_sz=369 77
win.Miss\ Piggy\ The\ Sow_pos=(598, 563)
win.Table_pos=(710, 607)
pref.fayte_hud_season_sz=74 74
win.Gembox_pos=(1358, 120)
win.Chest_pos=(652, 210)
win.Field_pos=(1380, 290)
win.Grand\ Bed_pos=(503, 222)
win.Shed_pos=(1559, 159)
win.Cask_pos=(662, 164)
win.Gemcutter's\ Wheel_pos=(420, 101)
win.Stack\ of\ Humus_pos=(200, 310)
pref.fayte_hud_shoplist_sz=333 149
pref.fayte_hud_buffs_sz=36 36
win.Urn_pos=(1305, 313)
win.Stack\ of\ Sand_pos=(515, 490)
win.NumericBelt_pos=(53, 152)
